
# ============================================================================
# FILE: 02_separable_nmf/app.R  
# ============================================================================

library(shiny)
library(shinydashboard)
library(ggplot2)
library(plotly)
library(DT)
library(viridis)

# Source shared functions
source("../shared/nmf_algorithms.R", local = TRUE)
source("../shared/visualization_helpers.R", local = TRUE)
source("../shared/sample_data.R", local = TRUE)

# UI
ui <- dashboardPage(
  dashboardHeader(title = "Separable NMF & Anchor Words Algorithm"),
  
  dashboardSidebar(
    sidebarMenu(
      menuItem("Geometric View", tabName = "geometric", icon = icon("cube")),
      menuItem("Separability Condition", tabName = "separability", icon = icon("crosshairs")),
      menuItem("Anchor Words Algorithm", tabName = "algorithm", icon = icon("cogs")),
      menuItem("Separable vs Non-Separable", tabName = "comparison", icon = icon("balance-scale"))
    )
  ),
  
  dashboardBody(
    tabItems(
      # Geometric View Tab
      tabItem(tabName = "geometric",
              fluidRow(
                box(width = 12, title = "Geometric Interpretation (Claim 2.3.2)", status = "primary", solidHeader = TRUE,
                    withMathJax("$M = AW \\Leftrightarrow C_M \\subseteq C_A$"),
                    p("Cone generated by columns of M is contained in cone generated by columns of A"),
                    
                    h4("Definition: Cone"),
                    withMathJax("$C_A = \\{Ax | x \\geq 0\\}$"),
                    p("All non-negative linear combinations of columns of A"),
                    
                    tags$ul(
                      tags$li(tags$b("Key Insight:"), "If we know A, finding W is easy (linear programming)"),
                      tags$li(tags$b("Hard Part:"), "Both A and W are unknown")
                    )
                )
              ),
              
              fluidRow(
                box(width = 12, title = "Word Vectors in Topic Space", status = "info", solidHeader = TRUE,
                    plotOutput("geometric_plot", height = "500px"),
                    p("🔴 Red points: Anchor words (extreme points of convex hull)", br(),
                      "🔵 Blue points: Regular words (interior points)")
                )
              )
      ),
      
      # Separability Tab
      tabItem(tabName = "separability",
              fluidRow(
                box(width = 6, title = "Example Selection", status = "primary", solidHeader = TRUE,
                    radioButtons("example_type", "Choose Example:",
                                 choices = list("Separable Matrix" = "separable",
                                                "Non-Separable Matrix" = "nonseparable"),
                                 selected = "separable")
                ),
                
                box(width = 6, title = "Separability Definition (2.3.11)", status = "info", solidHeader = TRUE,
                    h5("A is separable if:"),
                    p("For every topic i, there exists a word j where:"),
                    withMathJax("$A[j, i] > 0 \\text{ and } A[j, k] = 0 \\text{ for all } k \\neq i$"),
                    p(em("Word j is called an 'anchor word' for topic i"))
                )
              ),
              
              fluidRow(
                box(width = 8, title = "Topic Matrix A Analysis", status = "primary", solidHeader = TRUE,
                    h4("Topic Matrix A"),
                    DT::dataTableOutput("topic_matrix_table")
                ),
                
                box(width = 4, title = "Separability Check", status = "info", solidHeader = TRUE,
                    uiOutput("separability_status")
                )
              )
      ),
      
      # Algorithm Tab
      tabItem(tabName = "algorithm",
              fluidRow(
                box(width = 12, title = "Anchor Words Algorithm (Theorem 2.3.12)", status = "success", solidHeader = TRUE,
                    div(style = "text-align: center; background-color: #f0f9ff; padding: 15px; border-radius: 5px;",
                        h4("If M = AW where A is separable and W has full row rank, then we can recover A and W in polynomial time!")
                    )
                )
              ),
              
              fluidRow(
                box(width = 6, title = "Algorithm Steps", status = "primary", solidHeader = TRUE,
                    h5("Step-by-Step Process:"),
                    div(id = "algorithm_steps",
                        div(class = "step-box step-active", "1. Start with all word vectors (rows of M)"),
                        div(class = "step-box", "2. Check if each word is in convex hull of others"),
                        div(class = "step-box", "3. Remove words that are in convex hull"),
                        div(class = "step-box", "4. Remaining words are anchor words"),
                        div(class = "step-box", "5. Solve for A using anchor words")
                    ),
                    
                    br(),
                    actionButton("next_step", "Next Step", class = "btn-primary"),
                    actionButton("reset_algorithm", "Reset", class = "btn-secondary")
                ),
                
                box(width = 6, title = "Key Insight: Convex Hull", status = "info", solidHeader = TRUE,
                    h5("Why it works:"),
                    tags$ul(
                      tags$li("Anchor words are extreme points of convex hull"),
                      tags$li("Non-anchor words are inside the hull"),
                      tags$li("Iteratively remove interior points"),
                      tags$li("Remaining points are anchors")
                    ),
                    
                    div(style = "background-color: #e3f2fd; padding: 10px; border-radius: 5px;",
                        h6("Complexity Analysis:"),
                        p(tags$b("Time:"), "O(m³n) where m = words, n = documents", br(),
                          tags$b("Improvement:"), "Greedy furthest-point heuristic")
                    )
                )
              ),
              
              fluidRow(
                box(width = 12, title = "Practical Implementation Notes", status = "warning", solidHeader = TRUE,
                    tags$ul(
                      tags$li("Real matrices are rarely exactly separable"),
                      tags$li("Algorithm works with approximate separability"),
                      tags$li("Use greedy furthest-point algorithm for efficiency"), 
                      tags$li("Apply dimension reduction before anchor finding")
                    )
                )
              )
      ),
      
      # Comparison Tab
      tabItem(tabName = "comparison",
              fluidRow(
                box(width = 6, title = "✅ Separable Case", status = "success", solidHeader = TRUE,
                    div(
                      div(style = "background: white; padding: 10px; margin: 8px 0; border-radius: 4px; border: 1px solid #ddd;",
                          h6("Computational Complexity"), 
                          p("Polynomial time O(m³n)", style = "color: #2e7d32; margin: 0;")
                      ),
                      div(style = "background: white; padding: 10px; margin: 8px 0; border-radius: 4px; border: 1px solid #ddd;",
                          h6("Uniqueness"),
                          p("Unique solution (up to scaling)", style = "color: #2e7d32; margin: 0;")
                      ),
                      div(style = "background: white; padding: 10px; margin: 8px 0; border-radius: 4px; border: 1px solid #ddd;",
                          h6("Robustness"),
                          p("Works with approximate separability", style = "color: #2e7d32; margin: 0;")
                      ),
                      div(style = "background: white; padding: 10px; margin: 8px 0; border-radius: 4px; border: 1px solid #ddd;",
                          h6("Applications"),
                          p("Topic modeling with anchor words", style = "color: #2e7d32; margin: 0;")
                      )
                    )
                ),
                
                box(width = 6, title = "❌ General NMF", status = "danger", solidHeader = TRUE,
                    div(
                      div(style = "background: white; padding: 10px; margin: 8px 0; border-radius: 4px; border: 1px solid #ddd;",
                          h6("Computational Complexity"),
                          p("NP-hard", style = "color: #c62828; margin: 0;")
                      ),
                      div(style = "background: white; padding: 10px; margin: 8px 0; border-radius: 4px; border: 1px solid #ddd;",
                          h6("Uniqueness"),
                          p("Multiple local optima", style = "color: #c62828; margin: 0;")
                      ),
                      div(style = "background: white; padding: 10px; margin: 8px 0; border-radius: 4px; border: 1px solid #ddd;",
                          h6("Robustness"),
                          p("Sensitive to initialization", style = "color: #c62828; margin: 0;")
                      ),
                      div(style = "background: white; padding: 10px; margin: 8px 0; border-radius: 4px; border: 1px solid #ddd;",
                          h6("Applications"),
                          p("Heuristic alternating minimization", style = "color: #c62828; margin: 0;")
                      )
                    )
                )
              ),
              
              fluidRow(
                box(width = 12, title = "Real-World Performance", status = "primary", solidHeader = TRUE,
                    fluidRow(
                      column(6,
                             h4("Experimental Results (Section 2.4)"),
                             tags$ul(
                               tags$li("UCI Dataset: 300K NY Times articles"),
                               tags$li("0.9 fraction of topics had near-anchor words"),
                               tags$li("Anchor algorithm: hundreds of times faster than MALLET"),
                               tags$li("Comparable or better topic quality")
                             )
                      ),
                      column(6,
                             h4("When to Use Each Approach"),
                             tags$ul(
                               tags$li(tags$b("Separable NMF:"), "When topics have exclusive vocabulary"),
                               tags$li(tags$b("General NMF:"), "When all words are shared across topics"),
                               tags$li(tags$b("Hybrid:"), "Use anchor words as initialization for general NMF")
                             )
                      )
                    )
                )
              )
      )
    ),
    
    # Custom CSS
    tags$head(tags$style(HTML("
      .step-box {
        background-color: #f5f5f5;
        border-left: 4px solid #ddd;
        padding: 10px;
        margin: 8px 0;
        border-radius: 4px;
        transition: all 0.3s;
      }
      .step-active {
        background-color: #e8f5e8;
        border-left-color: #4caf50;
        color: #2e7d32;
        font-weight: bold;
      }
    ")))
  )
)

# Server
server <- function(input, output, session) {
  
  # Reactive values
  values <- reactiveValues(
    current_step = 1,
    separable_data = NULL,
    nonseparable_data = NULL
  )
  
  # Initialize data
  observe({
    # Separable example
    topic_data_sep <- generate_separable_topics(num_topics = 3, vocab_size = 12, separability = 0.9)
    values$separable_data <- list(
      A = topic_data_sep$A,
      vocabulary = topic_data_sep$vocabulary,
      anchor_words = topic_data_sep$anchor_words,
      name = "Separable Matrix"
    )
    
    # Non-separable example
    topic_data_nonsep <- generate_separable_topics(num_topics = 3, vocab_size = 12, separability = 0.3)
    # Make it more non-separable
    A_nonsep <- topic_data_nonsep$A
    A_nonsep <- A_nonsep + matrix(runif(nrow(A_nonsep) * ncol(A_nonsep), 0, 0.2), 
                                  nrow = nrow(A_nonsep))
    A_nonsep <- apply(A_nonsep, 2, function(x) x / sum(x))
    
    values$nonseparable_data <- list(
      A = A_nonsep,
      vocabulary = topic_data_nonsep$vocabulary,
      anchor_words = c(),  # No clear anchors
      name = "Non-Separable Matrix"
    )
  })
  
  # Get current example data
  current_data <- reactive({
    if (input$example_type == "separable") {
      values$separable_data
    } else {
      values$nonseparable_data
    }
  })
  
  # Geometric plot
  output$geometric_plot <- renderPlot({
    req(current_data())
    data <- current_data()
    plot_separability_scatter(data$A, data$vocabulary, data$anchor_words)
  }, height = 500)
  
  # Topic matrix table
  output$topic_matrix_table <- DT::renderDataTable({
    req(current_data())
    data <- current_data()
    
    # Create display matrix
    display_matrix <- data.frame(
      Word = data$vocabulary,
      Topic1 = round(data$A[, 1], 2),
      Topic2 = round(data$A[, 2], 2),
      Topic3 = round(data$A[, 3], 2),
      IsAnchor = 1:nrow(data$A) %in% data$anchor_words
    )
    
    display_matrix
  }, options = list(pageLength = 15, scrollY = "400px", scrollCollapse = TRUE)) %>%
    formatStyle("IsAnchor", backgroundColor = styleEqual(TRUE, "#c8e6c9"))
  
  # Separability status
  output$separability_status <- renderUI({
    req(current_data())
    data <- current_data()
    
    if (length(data$anchor_words) > 0) {
      # Separable case
      anchor_text <- paste0("Topic ", seq_along(data$anchor_words), ": ", 
                            data$vocabulary[data$anchor_words], collapse = "<br/>")
      
      div(style = "background-color: #e8f5e8; padding: 15px; border: 2px solid #4caf50; border-radius: 8px;",
          h5("✅ Matrix is Separable!", style = "color: #2e7d32; margin-bottom: 10px;"),
          HTML(anchor_text)
      )
    } else {
      # Non-separable case
      div(style = "background-color: #ffebee; padding: 15px; border: 2px solid #f44336; border-radius: 8px;",
          h5("❌ Matrix is NOT Separable", style = "color: #c62828; margin-bottom: 10px;"),
          p("No topic has a clear anchor word (exclusive vocabulary)", style = "color: #c62828;")
      )
    }
  })
  
  # Algorithm step control
  observeEvent(input$next_step, {
    if (values$current_step < 5) {
      values$current_step <- values$current_step + 1
      
      # Update step styling with JavaScript
      session$sendCustomMessage("updateStep", values$current_step)
    }
  })
  
  observeEvent(input$reset_algorithm, {
    values$current_step <- 1
    session$sendCustomMessage("resetSteps", "")
  })
  
  # JavaScript for step updates
  session$onSessionEnded(function() {
    tags$script("
      Shiny.addCustomMessageHandler('updateStep', function(step) {
        $('.step-box').removeClass('step-active');
        $('.step-box:nth-child(' + step + ')').addClass('step-active');
      });
      
      Shiny.addCustomMessageHandler('resetSteps', function(message) {
        $('.step-box').removeClass('step-active');
        $('.step-box:first-child').addClass('step-active');
      });
    ")
  })
}

# Run app
shinyApp(ui = ui, server = server)
